In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset['charges']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet

param_grid = {
    'alpha': [0.001, 0.01, 0.1, 1.0, 10.0, 100.0],
    'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]}

grid = GridSearchCV(ElasticNet(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

GridSearchCV(estimator=ElasticNet(), n_jobs=-1,
             param_grid={'alpha': [0.001, 0.01, 0.1, 1.0, 10.0, 100.0],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'alpha': 10.0, 'l1_ratio': 1.0}:

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.042750,0.026360,0.003933,0.001993,0.001,0.1,"{'alpha': 0.001, 'l1_ratio': 0.1}",0.761147,0.709064,0.774968,0.731702,0.756301,0.746636,0.023415,10
1,0.020649,0.021258,0.002850,0.001852,0.001,0.3,"{'alpha': 0.001, 'l1_ratio': 0.3}",0.761113,0.708994,0.775107,0.731631,0.756359,0.746641,0.023481,9
2,0.006558,0.002931,0.003906,0.001629,0.001,0.5,"{'alpha': 0.001, 'l1_ratio': 0.5}",0.761078,0.708922,0.775245,0.731558,0.756414,0.746643,0.023547,4
3,0.006408,0.000979,0.004758,0.001772,0.001,0.7,"{'alpha': 0.001, 'l1_ratio': 0.7}",0.761040,0.708848,0.775382,0.731483,0.756468,0.746644,0.023613,3
4,0.007175,0.001898,0.005890,0.001540,0.001,0.9,"{'alpha': 0.001, 'l1_ratio': 0.9}",0.761000,0.708772,0.775517,0.731406,0.756519,0.746643,0.023680,5
5,0.008529,0.000602,0.006316,0.000917,0.001,1.0,"{'alpha': 0.001, 'l1_ratio': 1.0}",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,8
6,0.009533,0.000996,0.006107,0.001551,0.010,0.1,"{'alpha': 0.01, 'l1_ratio': 0.1}",0.760820,0.710373,0.768378,0.732898,0.752625,0.745019,0.020978,16
7,0.010777,0.004914,0.007048,0.002374,0.010,0.3,"{'alpha': 0.01, 'l1_ratio': 0.3}",0.761183,0.710306,0.770163,0.732882,0.753760,0.745659,0.021541,15
8,0.004114,0.002648,0.002630,0.001698,0.010,0.5,"{'alpha': 0.01, 'l1_ratio': 0.5}",0.761370,0.710079,0.771850,0.732692,0.754754,0.746149,0.022129,14
9,0.009291,0.002766,0.007317,0.002440,0.010,0.7,"{'alpha': 0.01, 'l1_ratio': 0.7}",0.761368,0.709681,0.773431,0.732315,0.755595,0.746478,0.022742,13
10,0.011775,0.005367,0.007425,0.002854,0.010,0.9,"{'alpha': 0.01, 'l1_ratio': 0.9}",0.761163,0.709098,0.774897,0.731736,0.756272,0.746633,0.023382,11
11,0.014267,0.001801,0.007956,0.001833,0.010,1.0,"{'alpha': 0.01, 'l1_ratio': 1.0}",0.760979,0.708734,0.775584,0.731367,0.756545,0.746642,0.023713,7
12,0.013562,0.002197,0.008076,0.000341,0.100,0.1,"{'alpha': 0.1, 'l1_ratio': 0.1}",0.684226,0.652716,0.667799,0.669717,0.660578,0.667007,0.010489,21
13,0.009640,0.002183,0.005251,0.001264,0.100,0.3,"{'alpha': 0.1, 'l1_ratio': 0.3}",0.707604,0.671858,0.693640,0.690288,0.686038,0.689886,0.011559,20
14,0.008649,0.001215,0.006588,0.000820,0.100,0.5,"{'alpha': 0.1, 'l1_ratio': 0.5}",0.729987,0.689558,0.719969,0.709511,0.711292,0.712063,0.013397,19
15,0.008092,0.001738,0.004970,0.001656,0.100,0.7,"{'alpha': 0.1, 'l1_ratio': 0.7}",0.749108,0.703700,0.745467,0.725127,0.734499,0.731580,0.016294,18
16,0.007712,0.002137,0.004950,0.001630,0.100,0.9,"{'alpha': 0.1, 'l1_ratio': 0.9}",0.760576,0.710350,0.767450,0.732843,0.752006,0.744645,0.020705,17
17,0.008288,0.001843,0.006081,0.001487,0.100,1.0,"{'alpha': 0.1, 'l1_ratio': 1.0}",0.760981,0.708736,0.775583,0.731368,0.756544,0.746642,0.023712,6
18,0.007640,0.000380,0.004688,0.001420,1.000,0.1,"{'alpha': 1.0, 'l1_ratio': 0.1}",0.302202,0.307056,0.287368,0.312867,0.268660,0.295630,0.015916,26
19,0.006896,0.001543,0.004640,0.000557,1.000,0.3,"{'alpha': 1.0, 'l1_ratio': 0.3}",0.339987,0.343066,0.324373,0.349287,0.307085,0.332760,0.015239,25
20,0.008119,0.001873,0.003601,0.000509,1.000,0.5,"{'alpha': 1.0, 'l1_ratio': 0.5}",0.397381,0.397090,0.380454,0.404137,0.365330,0.388878,0.014128,24
21,0.007452,0.001631,0.004180,0.000718,1.000,0.7,"{'alpha': 1.0, 'l1_ratio': 0.7}",0.493659,0.485841,0.474699,0.495003,0.463101,0.482461,0.012076,23
22,0.007310,0.001602,0.005475,0.001361,1.000,0.9,"{'alpha': 1.0, 'l1_ratio': 0.9}",0.672481,0.642937,0.655210,0.659267,0.648003,0.655580,0.010165,22
23,0.007003,0.001453,0.005154,0.001352,1.000,1.0,"{'alpha': 1.0, 'l1_ratio': 1.0}",0.761000,0.708758,0.775569,0.731382,0.756537,0.746649,0.023702,2
24,0.006541,0.001125,0.003927,0.001074,10.000,0.1,"{'alpha': 10.0, 'l1_ratio': 0.1}",0.143438,0.153451,0.128437,0.154763,0.104677,0.136953,0.018685,31
25,0.006008,0.000783,0.005080,0.001560,10.000,0.3,"{'alpha': 10.0, 'l1_ratio': 0.3}",0.149928,0.159438,0.135285,0.161708,0.111514,0.143575,0.018533,30
26,0.006326,0.001523,0.003918,0.000708,10.000,0.5,"{'alpha': 10.0, 'l1_ratio': 0.5}",0.161046,0.170005,0.146819,0.173304,0.123219,0.154878,0.018295,29
27,0.006057,0.000848,0.004286,0.000714,10.000,0.7,"{'alpha': 10.0, 'l1_ratio': 0.7}",0.185446,0.193739,0.171652,0.198112,0.148735,0.179537,0.017847,28
28,0.008130,0.001709,0.004758,0.000740,10.000,0.9,"{'alpha': 10.0, 'l1_ratio': 0.9}",0.287392,0.292889,0.272860,0.298526,0.253566,0.281047,0.016175,27
29,0.006719,0.001270,0.004489,0.000758,10.000,1.0,"{'alpha': 10.0, 'l1_ratio': 1.0}",0.761183,0.708975,0.775431,0.731512,0.756463,0.746713,0.023598,1
30,0.007414,0.001354,0.005167,0.000855,100.000,0.1,"{'alpha': 100.0, 'l1_ratio': 0.1}",0.102290,0.117115,0.086635,0.106447,0.070108,0.096519,0.016440,36
31,0.008102,0.001876,0.005603,0.000468,100.000,0.3,"{'alpha': 100.0, 'l1_ratio': 0.3}",0.107818,0.122598,0.091495,0.112762,0.073490,0.101633,0.017300,35
32,0.007398,0.001225,0.004877,0.000312,100.000,0.5,"{'alpha': 100.0, 'l1_ratio': 0.5}",0.114226,0.128610,0.097430,0.120327,0.077691,0.107657,0.018140,34
33,0.007628,0.000498,0.005662,0.000678,100.000,0.7,"{'alpha': 100.0, 'l1_ratio': 0.7}",0.122413,0.135672,0.105676,0.130326,0.083914,0.115600,0.018808,33
34,0.008142,0.001610,0.005000,0.000597,100.000,0.9,"{'alpha': 100.0, 'l1_ratio': 0.9}",0.140446,0.150786,0.125252,0.151471,0.101501,0.133891,0.018768,32
35,0.007155,0.000900,0.003913,0.000742,100.000,1.0,"{'alpha': 100.0, 'l1_ratio': 1.0}",0.762172,0.710552,0.772687,0.732342,0.754922,0.746535,0.022338,12

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [13]:
Future_Preduction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Preduction={}".format(Future_Preduction))

Future_Preduction=[10901.14214845]

C:\Users\Deepa Devi K\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(